[package]
name = "bcachefs-fstab-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
fstab = "0.4.0"
libsystemd-sys = { version = "0.9.3", default-features = false }
systemd = { version = "0.10.0", default-features = false }
